// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SyllabusService.Infrastructure.Models;

namespace SyllabusService.Infrastructure.DBContext;

public partial class PES_APP_FULL_DBContext : DbContext
{
    public PES_APP_FULL_DBContext(DbContextOptions<PES_APP_FULL_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }
    public virtual DbSet<Activity> Activities { get; set; }
    public virtual DbSet<Syllabus> Syllabi { get; set; }

    public virtual DbSet<AdmissionTerm> AdmissionTerms { get; set; }

    public virtual DbSet<PatternActivity> PatternActivities { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__classes__3213E83FBB957C05");

            entity.ToTable("classes");

            entity.Property(e => e.Id).HasColumnName("id").UseIdentityColumn();
            entity.Property(e => e.AcademicYear).HasColumnName("academic_year");
            entity.Property(e => e.AdmissionTermId).HasColumnName("admission_term_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.CreatedAt).HasColumnName("createdAt");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.NumberOfWeeks).HasColumnName("number_of_weeks");
            entity.Property(e => e.NumberStudent).HasColumnName("number_student");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.SyllabusId).HasColumnName("syllabus_id");
            entity.Property(e => e.Version).HasColumnName("version");
            entity.Property(e => e.TeacherId).HasColumnName("teacher_id");

            entity.HasOne(d => d.AdmissionTerm).WithMany(p => p.Classes)
                .HasForeignKey(d => d.AdmissionTermId)
                .HasConstraintName("FK_classes_AdmissionTerm");

            entity.HasOne(d => d.Syllabus).WithMany(p => p.Classes)
                .HasForeignKey(d => d.SyllabusId)
                .HasConstraintName("FK_classes_syllabus");
        });

        modelBuilder.Entity<AdmissionTerm>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__term_ite__3213E83F8D70FB89");

            entity.ToTable("AdmissionTerm");

            entity.Property(e => e.Id).HasColumnName("id")
            .UseIdentityColumn();
            entity.Property(e => e.AcdemicYear).HasColumnName("acdemicYear");
            entity.Property(e => e.CurrentRegisteredStudents).HasColumnName("currentRegisteredStudents");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("endDate");
            entity.Property(e => e.MaxNumberRegistration).HasColumnName("maxNumberRegistration");
            entity.Property(e => e.NumberOfClasses).HasColumnName("numberOfClasses");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<PatternActivity>(entity =>
        {

            entity.ToTable("PatternActivities");

            entity.Property(e => e.Id)
                .UseIdentityColumn()
                .HasColumnName("id");
            entity.Property(e => e.ClassId).HasColumnName("classId");
            entity.Property(e => e.DayOfWeek)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("dayOfWeek");
            entity.Property(e => e.EndTime).HasColumnName("endTime");
            entity.Property(e => e.StartTime).HasColumnName("startTime");

            entity.HasOne(d => d.Class).WithMany(p => p.PatternActivities)
                .HasForeignKey(d => d.ClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PatternActivities_classes");
        });
        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__schedule__3213E83F8AC4974E");

            entity.ToTable("schedule");

            entity.Property(e => e.Id).HasColumnName("id").UseIdentityColumn();
            entity.Property(e => e.ClassesId).HasColumnName("classes_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("endDate");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("startDate");
            entity.Property(e => e.WeekName)
                .HasMaxLength(50)
                .HasColumnName("week_name");

            entity.HasOne(d => d.Classes).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.ClassesId)
                .HasConstraintName("FK_schedule_classes");
        });

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__activity__3213E83F7D6F1DEE");

            entity.ToTable("activity");

            entity.Property(e => e.Id).HasColumnName("id").UseIdentityColumn();
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.DayOfWeek)
            .HasMaxLength(50)
            .HasColumnName("day_of_week");
            entity.Property(e => e.EndTime)
                .HasPrecision(6)
                .HasColumnName("end_time");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.ScheduleId).HasColumnName("schedule_id");
            entity.Property(e => e.StartTime)
                .HasPrecision(6)
                .HasColumnName("start_time");

            entity.HasOne(d => d.Schedule).WithMany(p => p.Activities)
                .HasForeignKey(d => d.ScheduleId)
                .HasConstraintName("FK_activity_schedule");
        });

        modelBuilder.Entity<Syllabus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__syllabus__3213E83F32436D12");

            entity.ToTable("syllabus");

            entity.Property(e => e.Id).HasColumnName("id").UseIdentityColumn();
            entity.Property(e => e.Name)
             .HasMaxLength(254)
             .HasColumnName("name");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(6)
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(2000)
                .HasColumnName("description");
            entity.Property(e => e.Cost).HasColumnName("cost");
            entity.Property(e => e.HoursOfSyllabus).HasColumnName("hours_of_syllabus");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}