// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TermAdmissionManagement.Infrastructure.Entities;

public partial class AdmissionForm
{
    public int Id { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public string? CancelReason { get; set; }

    public string ChildCharacteristicsFormImg { get; set; }

    public string CommitmentImg { get; set; }

    public string HouseholdRegistrationAddress { get; set; }

    public string Note { get; set; }

    public DateTime? PaymentExpiryDate { get; set; }

    public string Status { get; set; }

    public DateTime? SubmittedDate { get; set; }

    public int? ParentAccountId { get; set; }

    public int? StudentId { get; set; }

    public int? TermItemId { get; set; }

    public virtual TermItem TermItem { get; set; }


}