    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
    #nullable disable
    using System;
    using System.Collections.Generic;

    namespace Auth.Repositories.Models;

    public partial class Account
    {
        public int Id { get; set; }

        public string Address { get; set; }

        public string AvatarUrl { get; set; }

        public DateTime? CreatedAt { get; set; }

        public string Email { get; set; }

        public bool? FirstLogin { get; set; }

        public string Gender { get; set; }

        public string IdentityNumber { get; set; }

        public string Name { get; set; }

        public string Password { get; set; }

        public string Phone { get; set; }

        public string Role { get; set; } // 'EDUCATION', 'HR', 'PARENT', 'TEACHER'

    public string Status { get; set; }
    }