services:
  authservice.api:
     environment:
      - ASPNETCORE_HTTP_PORTS=5022
     ports:
      - "5022:5022"
  termadmissionmanagement.api:
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"   # HTTP
  gateway.api:
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
   