// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParentService.Infrastructure.Models;

public partial class StudentClass
{
    public int Id { get; set; }

    public int? ClassesId { get; set; }

    public int? StudentId { get; set; }

    public virtual Student Student { get; set; }
}