// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParentService.Infrastructure.Models;

public partial class Student
{
    public int Id { get; set; }

    public string BirthCertificateImg { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string HouseholdRegistrationImg { get; set; }

    public string Gender { get; set; }

    public string Name { get; set; }

    public string PlaceOfBirth { get; set; }

    public string ProfileImage { get; set; }

    public bool IsStudent { get; set; }

    public int? ParentAccId { get; set; }

    public virtual ICollection<AdmissionForm> AdmissionForms { get; set; } = new List<AdmissionForm>();

    public virtual ICollection<StudentClass> StudentClasses { get; set; } = new List<StudentClass>();
}