// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParentService.Infrastructure.Models;

public partial class TransactionItem
{
    public int Id { get; set; }

    public int TransactionId { get; set; }

    public string Name { get; set; }

    public int Cost { get; set; }

    public virtual Transaction Transaction { get; set; }
}