// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParentService.Infrastructure.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public long Amount { get; set; }

    public string Description { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public string Status { get; set; }

    public int FormId { get; set; }

    public virtual ICollection<TransactionItem> TransactionItems { get; set; } = new List<TransactionItem>();
}