// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class Activity
{
    public int Id { get; set; }

    public DateOnly? Date { get; set; }

    public string DayOfWeek { get; set; }

    public TimeOnly? EndTime { get; set; }

    public TimeOnly? StartTime { get; set; }

    public string Name { get; set; }

    public int? ScheduleId { get; set; }

    public virtual Schedule Schedule { get; set; }
}