// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class AdmissionFormClass
{
    public int AdmissionFormId { get; set; }

    public int ClassId { get; set; }

    public virtual AdmissionForm AdmissionForm { get; set; }
}