// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class AdmissionForm
{
    public int Id { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public string CancelReason { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public DateTime? SubmittedDate { get; set; }

    public int AdmissionTermId { get; set; }

    public int? ParentAccountId { get; set; }

    public int? StudentId { get; set; }

    public virtual AdmissionTerm AdmissionTerm { get; set; }
}