// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class AdmissionTerm
{
    public int Id { get; set; }

    public int? AcdemicYear { get; set; }

    public int? MaxNumberRegistration { get; set; }

    public int? CurrentRegisteredStudents { get; set; }

    public int? NumberOfClasses { get; set; }

    public string Status { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual ICollection<AdmissionForm> AdmissionForms { get; set; } = new List<AdmissionForm>();

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();
}