// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class PatternActivity
{
    public int Id { get; set; }

    public string DayOfWeek { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int ClassId { get; set; }

    public virtual Class Class { get; set; }
}