// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyllabusService.Infrastructure.Models;

public partial class Syllabus
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Description { get; set; }

    public int? Cost { get; set; }

    public int HoursOfSyllabus { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();
}