// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auth.Domain.Entities
{
    public class Class
    {
        public int Id { get; set; }

        public int? AcademicYear { get; set; }

        public DateOnly? EndDate { get; set; }


        public string Name { get; set; }

        public int? NumberStudent { get; set; }

        public DateOnly? StartDate { get; set; }

        public string Status { get; set; }

        public int? SyllabusId { get; set; }

        public int? TeacherId { get; set; }

        public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

        public virtual Account Teacher { get; set; }
    }
}