// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auth.Domain.Entities
{

    public class Schedule
    {
        public int Id { get; set; }

        public string WeekName { get; set; }

        public int? ClassesId { get; set; }

        public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

        public virtual Class Classes { get; set; }
    }
}