name: Trigger auto deployment for pesapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pesapp-AutoDeployTrigger-e9f039b7-996e-4df1-b11c-80fe0e3fdf78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PESAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PESAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PESAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.PESAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PESAPP_REGISTRY_PASSWORD }}
          containerAppName: pesapp
          containerAppContainerName: pesapp
          resourceGroup: backend_server_management
          imageToBuild: huatri/pesapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_




