name: Trigger auto deployment for pesapp

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/pesapp-AutoDeployTrigger-e9f039b7-996e-4df1-b11c-80fe0e3fdf78.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PESAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PESAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PESAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login
        run: echo ${{ secrets.PESAPP_REGISTRY_PASSWORD }} | docker login docker.io -u ${{ secrets.PESAPP_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push container image
        run: |
          docker build -t huatri/gatewayapi:${{ github.sha }} -f ./Gateway.API/Dockerfile .
          docker push huatri/gatewayapi:${{ github.sha }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name pesapp \
            --resource-group backend_server_management \
            --image docker.io/huatri/gatewayapi:${{ github.sha }} \
            --container-name gatewayapi \
            --output none
