name: Trigger auto deployment for pesapp

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/pesapp-AutoDeployTrigger-e9f039b7-996e-4df1-b11c-80fe0e3fdf78.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PESAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PESAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PESAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login
        run: echo ${{ secrets.PESAPP_REGISTRY_PASSWORD }} | docker login docker.io -u ${{ secrets.PESAPP_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push authapi image
        run: |
          docker build -t huatri/authserviceapi:latest -f ./AuthService.API/Dockerfile .
          docker push huatri/authserviceapi:latest

      - name: Build and push admissionapi image
        run: |
          docker build -t huatri/termadmissionmanagementapi:latest -f ./TermAdmissionManagement.API/Dockerfile .
          docker push huatri/termadmissionmanagementapi:latest
       
      - name: Build and push syllabusapi image
        run: |
          docker build -t huatri/syllabusserviceapi -f ./SyllabusService.API/Dockerfile .
          docker push huatri/syllabusserviceapi:latest

      - name: Build and push gateway image
        run: |
          docker build -t huatri/gatewayapi:latest -f ./Gateway.API/Dockerfile .
          docker push huatri/gatewayapi:latest
          
      - name: Deploy authapi container
        run: |
          az containerapp update \
            --name pesapp \
            --resource-group backend_server_management \
            --image docker.io/huatri/authserviceapi:latest \
            --container-name authapi \
            --output none

      - name: Deploy admissionapi container
        run: |
          az containerapp update \
            --name pesapp \
            --resource-group backend_server_management \
            --image docker.io/huatri/termadmissionmanagementapi:latest \
            --container-name admissionapi \
            --output none
            
      - name: Deploy syllabusapi container
        run: |
          az containerapp update \
            --name pesapp \
            --resource-group backend_server_management \
            --image docker.io/huatri/syllabusserviceapi:latest \
            --container-name syllabusapi \
            --output none
            
      - name: Deploy gatewayapi container
        run: |
          az containerapp update \
            --name pesapp \
            --resource-group backend_server_management \
            --image docker.io/huatri/gatewayapi:latest \
            --container-name gatewayapi \
            --output none



